site_name: Quadruped Kinematics Library Docs

# github repository icon setup
repo_url: https://github.com/seanboe/QuadrupedKinematics
repo_name: QuadrupedKinematics

# edit button specs (right now, the edit is enabled)
# edit_uri: ""

copyright: Copyright &copy; 2021 Sean Boerhout

# Code Highlighting
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences


# Site navigation
nav:
  - About: 'index.md'
  - 'Kinematics Library': 'Kinematics-library.md'

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.integrate
  extra:
    generator: false
  #   analytics:
  #     provider: google
  #     property: 